# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('server', '0001_initial'), ('server', '0002_auto_20160206_0601'), ('server', '0003_auto_20160206_0611')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=50)),
                ('case_type', models.CharField(blank=True, max_length=50)),
                ('last_date', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocketEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('file', models.CharField(blank=True, max_length=50, null=True)),
                ('case', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='server.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('party_type', models.CharField(blank=True, max_length=50)),
                ('side', models.CharField(blank=True, max_length=50)),
                ('case', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='server.Case')),
            ],
        ),
    ]
