# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocketEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('file', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('party_type', models.CharField(blank=True, max_length=50)),
                ('side', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='last_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
