# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160206_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='docketentry',
            name='case',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='server.Case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='case',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='server.Case'),
            preserve_default=False,
        ),
    ]
